#!/bin/bash
# makes directories and sets up symlinks

mkdir -p log
mkdir -p datfiles
mkdir -p matrix/rootfiles
mkdir -p pdf_bXings_fills
mkdir -p pdf_bXings_runs
mkdir -p pdfs
mkdir -p png_rellum

touch sca2012t; rm sca2012t
ln -sv /GreyDisk1/sca2012t sca2012t

touch spinpat; rm spinpat
ln -sv ../fmstxt/spinpat spinpat

touch pol.root; rm pol.root
ln -sv ../polar12t/pol.root pol.root
